### ISSUE TITLE
Get the continous deployment pipeline setup 

### ISSUE THREAD

**Issue by andreasohlund** [ParticularLabs/APIComparer#12]
Proposed plan of attack:

1. Make the buildserver run octopack
2. Autodeploy to a -test environment on each commit to master
3. Promote to live via the octopus UI

Seems like the this is the best instructions I've found so far:

http://octopusdeploy.com/blog/deploy-aspnet-applications-to-azure-websites

other ideas/comments?

cc @ParticularLabs/apicomparer

**Comment by SeanFeldman** [comment]
+1 for test slot. We'll need to switch website to standard tear to have slots available. It would also allow Production Testing (slot routing) aka A/B testing.

**Comment by andreasohlund** [comment]
Some progress. Got the Octopus package created now and working on setting up the auto deploy to test

**Comment by danielmarbach** [comment]
Yeah!

**Comment by andreasohlund** [comment]
This is now done. Each commit is now deployed to test. 

 Added a brief readme : https://github.com/ParticularLabs/APIComparer/blob/master/README.md
