### ISSUE TITLE
Production and test environments

### ISSUE THREAD

**Issue by SeanFeldman** [ParticularLabs/APIComparer#13]
We should look into production and test slots rather than running 2 different websites.

**Plan of attack**
- [x] Create a resource group
 - [x] Add geo-redundant storage
 - [x] Add a standard web hosting site
  -[x] add test slot (`Production` is default)
   - [x] add sticky settings to each slot (connection strings)

**Comment by SeanFeldman** [comment]
In addition to that, we should have group storage account and website under resource group so that it would be easier to manage it

**Comment by andreasohlund** [comment]
Can you still have separate configs for each slot? (eg use different storage accounts)

**Comment by SeanFeldman** [comment]
Absolutely @andreasohlund 
You can instruct what settings stick to a slot.

**Comment by andreasohlund** [comment]
Cool, lets go ahead with this then. We need to modify octopus to do a slot swap instead when promoting to live

**Comment by SeanFeldman** [comment]
Added plan of attack. Deployment with slots is slightly different from the deployment strategy we're today, so we'd need to decide how we'll go about swap (or promoting to production).

**Comment by andreasohlund** [comment]
Looks good. 

In short: auto deploy each commit to the test slot

On promote in octopus do a swap btw test and live slots

Question: since that would make the test slot stale should we modify the promote to use some kind of staging slot to leave test untouched?

**Comment by SeanFeldman** [comment]
Slots only available with paid options and we can have as many as 5 for lowest paid Standard tear.
How about having `-preview`, `-staging`, and regular `production` slots.
- `-preview` would get updated on every commit to master just like today.
- `-staging` would be used for staging, as intended, and allow to rollback if needed. This will address staleness since `-staging` is designated to be an intermediate step for `production`.

Since we're deploying to `production` slot manually, we could have it done in 2 steps behind the scene:
1. Create `-staging` slot
2. Deploy to `-staging` slot
3. Swap `-staging` and `production` slots
3.  Delete `-staging` slot

Downside of this approach is no option to rollback. Once can argue that if you've tested it, you shouldn't rollback.

**Comment by SeanFeldman** [comment]
@andreasohlund 
have create resource group `API-Comparer` under production subscription that contains website and storage. New setup should be done on the resource group.
![image](https://cloud.githubusercontent.com/assets/1309622/6770077/716405a8-d07a-11e4-8c9b-670c6b8e3f33.png)

**Comment by andreasohlund** [comment]
I like the 3 slot approach. Should we use "Test" or "Preview" for the
always updated one?
