### ISSUE TITLE
Add ability to provide nuget .NET framework `target` through request URL

### ISSUE THREAD

**Issue by SeanFeldman** [ParticularLabs/APIComparer#23]
So request for a default would be .NET 4.0 (we could append this ourselves)
```
http://apicomparer-preview.particular.net/compare/nservicebus.azure/5.0.0...6.0.0/net40
```
but an overridde would look like
```
http://apicomparer-preview.particular.net/compare/nservicebus.azure/5.0.0...6.0.0/net30
```
or
```
http://apicomparer-preview.particular.net/compare/newtonsoft.json/7.0.0...7.0.1/portable-net40+sl5+wp80+win8+wpa81
```

**Comment by SeanFeldman** [comment]
There's an edge case where leftVersion targets one version and rightVersion targets another version.
Example: `NServiceBus.Azure` 5.0.0 targets `net40` when `NServiceBus.Azure` 5.0.0 targets `net45`.

**Comment by SeanFeldman** [comment]
@ParticularLabs/apicomparer any idea how to instruct NancyFX to allow an optional module parameter that can contain the following `portable-net40+sl5+wp80+win8+wpa81`? It looks like nancy doesn't like the plus sign.

**Comment by danielmarbach** [comment]
Greedy regex route at the end?

**Comment by SeanFeldman** [comment]
Not using regex there

**Comment by ursenzler** [comment]
What when left version is built using a different .Net version/platform than right version?

**Comment by danielmarbach** [comment]
We discussed that comparing different .NET version doesn't make sense. Can you convince us otherwise?

**Comment by danielmarbach** [comment]
We discussed this today. We came to the following conclusion:

We compare nuget packages. So removing a target framework or changing a target framework can be considered as a breaking change in certain scenarios. We will be using the following algorithm

1. Download the nuget package
1. For every target on the leftVersion side we will compare against the matching target on the rightVersion side
1. In case when the rightVersion side does no longer have a target from the leftVersion side we consider this as a breaking change
1. In case when the rightVersion side has a target which is not existent on the leftVersion side we compare this target against the next higher target on the rightVersion side

## Examples

PackageFoo V1     PackageFoo V
NET35                     NET451
NET40                     NET45
                                 NET40

Report

NET451
NET45
NET40
NET35
Was removed. Breaking change.
