### ISSUE TITLE
Comparison doesn't show differences

### ISSUE THREAD

**Issue by philippdolder** [ParticularLabs/APIComparer#26]
When comparing http://apicomparer-preview.particular.net/Compare/Appccelerate.EventBroker/2.0.84...3.15.0 the new type `Internals.Subscriptions.NoArgumentsDelegateWrapper` isn't showing up.

**Comment by SeanFeldman** [comment]
@philippdolder I see the following

_The following types have differences._

Are you expecting a different result?

**Comment by philippdolder** [comment]
for the 3.1.0 to 3.15.0 comparison I would somehow expect ApiComparer to tell me it didn't find any differences. In that case the message maybe is just a bit confusing to me.

for the 2.0.84 to 3.15.0 comparison I would expect it to tell me that 3.15.0 is no longer compatible with .NET 4.0. And to tell me that there is a new type ```Internals.Subscriptions.NoArgumentsDelegateWrapper``` 
Not sure if that's the intention at all though

**Comment by andreasohlund** [comment]
Regarding http://apicomparer-preview.particular.net/Compare/Appccelerate.EventBroker/3.1.0...3.15.0 this is definitely a bug. We should show "No differences"

Regarding http://apicomparer-preview.particular.net/Compare/Appccelerate.EventBroker/2.0.84...3.15.0

1. Yes I think it makes sense that we show a breaking change in that there is no longer a .Net4.0 compatible version, @SimonCropp ?
2. Regarding `Internals.Subscriptions.NoArgumentsDelegateWrapper` is that type public? (we only check for public types)

**Comment by philippdolder** [comment]
2. yes ```Internals.Subscriptions.NoArgumentsDelegateWrapper``` is public (https://github.com/appccelerate/eventbroker/blob/master/source/Appccelerate.EventBroker/Internals/Subscriptions/NoArgumentsDelegateWrapper.cs)

**Comment by andreasohlund** [comment]
Ok, looks like a bug as well then!

**Comment by andreasohlund** [comment]
@philippdolder we'll change our comparisons to include all targets at all times including detecting changes in required targets and that should adress http://apicomparer-preview.particular.net/Compare/Appccelerate.EventBroker/2.0.84...3.15.0

I'll change the description of this bug to focus on the NoArgumentsDelegateWrapper not showing up

**Comment by philippdolder** [comment]
@andreasohlund should I open an issue for the "The following types have differences." instead of just showing something similar to "No differences." as well?

**Comment by andreasohlund** [comment]
Please do!

**Comment by andreasohlund** [comment]
@SimonCropp just double checking: In this case there was a new type added in the right version. Since that's isn't a change that could affect a upgrade I'm pretty sure we don't show it?

In short: I think this one is "by design"

Should we consider showing the new types? (not sure how valuable that would be though)

**Comment by SimonCropp** [comment]
@andreasohlund pretty sure api comparer used to show new apis?

**Comment by andreasohlund** [comment]
Ok, I'll investigate
