### ISSUE TITLE
Comparing between .NET framework targets

### ISSUE THREAD

**Issue by danielmarbach** [ParticularLabs/APIComparer#28]
We discussed this today #23. We came to the following conclusion:

We compare nuget packages. So removing a target framework or changing a target framework can be considered as a breaking change in certain scenarios. We will be using the following algorithm

1. Download the nuget package
1. For every target on the `leftVersion` side we will compare against the matching target on the `rightVersion` side
1. In case when the `rightVersion` side does no longer have a target from the `leftVersion` side we consider this as a breaking change
1. In case when the `rightVersion` side has a target which is not existent on the `leftVersion` side we compare this target against the highest target on the `leftVersion` side

## Examples

PackageFoo V1-------------PackageFoo V2
NET35--------------------------NET451
NET40--------------------------NET45
------------------------------------NET40

### Report
This is the comparison of PackageFoo V1 to PackageFoo V2. The comparison detected the following breaking and non-breaking changes.
#### NET35
Was removed. Breaking change.

**Comment by danielmarbach** [comment]
@ursenzler @philippdolder thoughts and additions from your side?

**Comment by philippdolder** [comment]
@danielmarbach looks good to me

**Comment by ursenzler** [comment]
Yes that would allow to compare versions with a .Net upgrade inbetween, e.g. leftVersion was built against 3.5 and rightVersion against 4.5. Which I consider a frequent case.

**Comment by andreasohlund** [comment]
I'll take a stab at this one

**Comment by andreasohlund** [comment]
@philippdolder http://apicomparer-preview.particular.net/Compare/Appccelerate.EventBroker/2.0.84...3.15.0 now shows the targets better, can you take a quick look?

Still need to figure out why the new type doesn't show as you mention in #34

**Comment by philippdolder** [comment]
@andreasohlund looks good
