### ISSUE TITLE
Multiple frameworks UI change

### ISSUE THREAD

**Issue by SeanFeldman** [ParticularLabs/APIComparer#53]
Would something like this be welcomed?

![image](https://cloud.githubusercontent.com/assets/1309622/10498052/a94cfdfe-7286-11e5-8530-938153cdacb3.png)

**Comment by andreasohlund** [comment]
Yes please :heart:

**Comment by SeanFeldman** [comment]
### Modification

- [ ] Emit extra html for tabs and static CSS for styling
- [ ] Fallback to original rendering if CSS is missing (offline HTML w/o CSS)

[Sample data](http://apicomparer.particular.net/compare/EntityFramework/6.0.0...6.1.3)
[Preview](http://codepen.io/heyvian/pen/vNeXeO)
