### ISSUE TITLE
GitVersionTask fails to tag master

### ISSUE THREAD

**Issue by SeanFeldman** [ParticularLabs/APIComparer#63]
Looks like PRs are getting a correct number, but when it's applied to `master`, something goes wrong. I've updated `GitVersionTask` from 3.0.0-beta to the latest and behavior is still the same.

![image](https://cloud.githubusercontent.com/assets/1309622/13376780/d0470fd4-dd80-11e5-9aea-2d37b4c2488a.png)

PR (#62) when merged into the `master` should generate tag 0.1.62, instead it's stuck on 0.1.48 which has been deployed to Octopus in the past and therefore auto-deployment fails.

@andreasohlund any ideas about `GitVersionTask`?

**Comment by SeanFeldman** [comment]
Emitted by TC on the failure:

Labeling failed for root 'GitHub.Master.PR'.
More details on[ build results page](https://builds.particular.net/viewLog.html?buildId=148861&buildTypeId=Tooling_APIComparer_1Build)

jetbrains.buildServer.vcs.VcsException: Labeling failed: org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={ object 59202f5881e81cd9d741f39dab5c86e8943232cb type commit tag 0.1.48 tagger PersonIdent[particularbot, , Sun Feb 28 01:32:15 2016 +0000] }' already exists at jetbrains.buildServer.buildTriggers.vcs.git.OperationContext.wrapException(OperationContext.java:177) at jetbrains.buildServer.buildTriggers.vcs.git.GitLabelingSupport.label(GitLabelingSupport.java:104) at jetbrains.vcs.api.services.impl.LabelingServiceProvider$1.label(LabelingServiceProvider.java:1) at jetbrains.buildServer.vcs.impl.VcsLabeler.doSetLabel(VcsLabeler.java:92) at jetbrains.buildServer.vcs.impl.VcsLabeler.access$400(VcsLabeler.java:6) at jetbrains.buildServer.vcs.impl.VcsLabeler$2$1.run(VcsLabeler.java:4) at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41) at jetbrains.buildServer.vcs.impl.VcsLabeler$2$2.run(VcsLabeler.java:3) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={ object 59202f5881e81cd9d741f39dab5c86e8943232cb type commit tag 0.1.48 tagger PersonIdent[particularbot, , Sun Feb 28 01:32:15 2016 +0000] }' already exists at org.eclipse.jgit.api.TagCommand.updateTagRef(TagCommand.java:199) at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:166) at jetbrains.buildServer.buildTriggers.vcs.git.GitLabelingSupport.label(GitLabelingSupport.java:92) ... 11 more

**Comment by andreasohlund** [comment]
We need to turn on continous deployment mode - https://gitversion.readthedocs.org/en/latest/reference/continuous-deployment/

I think we where relying on TC auto tagging in the past

**Comment by andreasohlund** [comment]
And if that works we can turn auto tagging off in TC

**Comment by SeanFeldman** [comment]
Need help - not sure how to specify the `mode` to the msbuild task.

**Comment by andreasohlund** [comment]
Not sure either, probably by setting some "mode" property
https://gitversion.readthedocs.org/en/latest/usage/msbuild-task/

**Comment by SeanFeldman** [comment]
Looks like there's a bug with this https://github.com/GitTools/GitVersion/issues/728

**Comment by SimonCropp** [comment]
@SeanFeldman can u monkey patch the dll with the code from here https://github.com/GitTools/GitVersion/issues/728#issuecomment-172325678 ?

**Comment by SeanFeldman** [comment]
@SimonCropp yes, that works. How would you suggest to include that as a nuget package?

**Comment by SimonCropp** [comment]
@SeanFeldman i think if u have verified the fix it would be enough to ping @JakeGinnivan to let him know

**Comment by SeanFeldman** [comment]
@SimonCropp I tried to verify it and results are inconclusive. Any chance you could try as well? Thank you.

**Comment by andreasohlund** [comment]
This is fixed now (we no longer need tagging)
