### ISSUE TITLE
Unknown custom metadata item kind: 7

### ISSUE THREAD

**Issue by DavidBoike** [ParticularLabs/APIComparer#72]
See http://apicomparer.particular.net/compare/RavenDB.Client/3.0.30155...3.5.0-rc-35169

> RavenDB.Client comparison between 3.0.30155 and 3.5.0-rc-35169 has failed with the following error: Unknown custom metadata item kind: 7

**Comment by andreasohlund** [comment]
Verified that this works locally. Wonder if have some stuff installed that makes this work?

**Comment by andreasohlund** [comment]
Works now, the nuget update we did a while back was the fix but the deploy was broken
