### ISSUE TITLE
Build breaks on r# validation failures in the webjobs settings file

### ISSUE THREAD

**Issue by andreasohlund** [ParticularLabs/APIComparer#80]
https://builds.particular.net/viewLog.html?buildId=193821&tab=Inspection&buildTypeId=Tooling_APIComparer_1Build

Not sure why this is happening now

**Comment by SeanFeldman** [comment]
Hmm, looks like R# code inspection is drunk. It fail on analysis of files it shouldn't have analysed to begin with.

**Comment by gbiellem** [comment]
nah it's not drunk - R# now validates js and json on the build server since the TC 10 update.  We'll need to adjust the dotsettings file to exclude them in the solution or fix the underlying issue it's found

**Comment by andreasohlund** [comment]
Fixed by https://github.com/ParticularLabs/APIComparer/commit/e1a929f4af6390717d10cda741733ed25e769f88
