### ISSUE TITLE
OutOfMemoryException on http://apicomparer.particular.net/compare/unity/5.3.2...5.4.0

### ISSUE THREAD

**Issue by ramonsmits** [ParticularLabs/APIComparer#82]
Getting an out of memory exception on http://apicomparer.particular.net/compare/unity/5.3.2...5.4.0

**Comment by andreasohlund** [comment]
I'll take a look

**Comment by ramonsmits** [comment]
I also have it with http://apicomparer.particular.net/compare/unity/5.3.2...5.5.0

**Comment by andreasohlund** [comment]
Works on the latest version 

http://apicomparer-preview.particular.net/compare/unity/5.3.2...5.5.0

I'll try to update it

**Comment by andreasohlund** [comment]
site updated, this now works

Side note: We need to now and then clean failed comparisons to retry them, will raise an issue
