### ISSUE TITLE
Reliably detect the root build dir to create links

### ISSUE THREAD

**Issue by andreasohlund** [ParticularLabs/APIComparer#9]
Right now we hardcoded to 4 which works on the buildserver but my machine needs 3 since the code is in c://dev

https://github.com/ParticularLabs/APIComparer/blob/master/APIComparer.Core/APIUpgradeToMarkdownFormatter.cs#L303

How can we make this work across the board?

@SimonCropp this is the bug we talked about yesterday

**Comment by SeanFeldman** [comment]
@andreasohlund is this relevant anymore?

**Comment by andreasohlund** [comment]
I think we have to go with manually configured roots for links so lets close this one.

Should we remove the links from the webpage until we have a way of generating them?
